name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.lock.yml
          cache-environment: true
      - name: Install the package
        run: pip install --no-deps -e .
      - name: Run tests
        run: python -m pytest -q tests
